# Base Configuration
baseURL=https://api.shopperstacks.com
environment=dev

# Admin User Credentials
admin_username=admin@example.com
admin_password=Admin@123

# Request Timeout (in seconds)
request_timeout=10

# Response Timeout (in seconds)
response_timeout=15

# Enable Logging
enable_logging=true

# Extent Reports Path
extent_report_path=./test-output/extent-reports/
