# Log4j2 Configuration
status = warn
name = ShopperStacksFramework

# Define appenders
appenders = console, file

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%-5p] %d{yyyy-MM-dd HH:mm:ss} [%t] %c{1} - %m%n

appender.file.type = File
appender.file.name = File
appender.file.fileName = ./test-output/app.log
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = [%-5p] %d{yyyy-MM-dd HH:mm:ss} [%t] %c{1} - %m%n

# Define root logger
rootLogger.level = info
rootLogger.appenderRefs = stdout, file
rootLogger.appenderRef.stdout.ref = STDOUT
rootLogger.appenderRe99f.file.ref = File
